version: '3'
services:
  dev:
    build:
      context: .
    image: simossyi/dev:neovim
    command: /bin/zsh
    volumes:
      - $WORK_DIR/:/root/workspace
      - $SSH_AUTH_SOCK/:/ssh-agent
      - .gitconfig:/root/.gitconfig
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    env_file:
      - .env
    working_dir: /root/workspace
    shm_size: 8g
