version: '3'
services:
  dev:
    build:
      context: .
    image: dev
    command: /bin/zsh
    volumes:
      - $WORK_DIR/:/root/workspace
      - $SSH_AUTH_SOCK/:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    env_file:
      - .env
    working_dir: /root/workspace
    shm_size: 8g
