# dein_lazy.toml is not loaded when you start vim
# it is recommended that you write the plugins that is not always used

# completement

# python settings

# autopepe8: python syntax checker
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'
hook_add = '''
    let g:autopep8_aggressive=2
    let g:autopep8_max_line_length=120
    let g:autopep8_ignore="E123,E126,E226,F541"
    let g:autopep8_on_save = 1
    let g:autopep8_disable_show_diff=1
'''

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = 'python'
build = 'make install'
hook_add = '''
  let g:pydocstring_formatter = 'google'
'''
