# dein_lazy.toml is not loaded when you start vim
# it is recommended that you write the plugins that is not always used

# completement

# python settings

# autopepe8: python syntax checker
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'
hook_add = '''
    let g:autopep8_aggressive=2
    let g:autopep8_max_line_length=120
    let g:autopep8_on_save = 1
    let g:autopep8_disable_show_diff=1
'''

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = 'python'
build = 'make install'
hook_add = '''
  let g:pydocstring_formatter = 'google'
'''

[[plugins]]
repo = 'psf/black'
on_ft = 'python'
hook_add = '''
  let g:black_linelength = 120
  let g:black_skip_string_normalization = 1
'''

# html

# automatically close tag
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'phtml']
hook_add = '''
  let g:closetag_filenames = '*.html,*.xhtml,*.phtml'
  let g:closetag_xhtml_filenames = '*.xhtml,*.jsx'
  let g:closetag_filetypes = 'html,xhtml,phtml'
  let g:closetag_xhtml_filetypes = 'xhtml,jsx'
  let g:closetag_emptyTags_caseSensitive = 1
  let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }
'''

# make rows into a list
# ul>li* : create list
# <C-y>d : select tag
# <C-y>k : delete tag
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'phtml']
